Section "ServerFlags"
	Option "AutoAddGPU" "false"
EndSection

Section "OutputClass"
	Identifier "SunxiDRM"
	MatchDriver "sunxi-drm"
	Driver "modesetting"
	Option "PrimaryGPU" "true"
	Option "AccelMethod" "none"
EndSection
