#!/bin/sh

set -e

case $1 in
install | upgrade)
	conflicts="
/usr/lib/xorg/modules/libglamoregl.so /usr/bin/Xorg
/usr/lib/xorg/modules/drivers/modesetting_drv.so
"
	for i in $conflicts; do
		dpkg-divert --package xserver-xorg-img-bxm-1.21.1-2.deb --divert "$i.bak" --rename "$i"
	done
	conflicts="
/usr/share/wayland-sessions/plasma.desktop /usr/bin/plasma-discover /usr/bin/sddm-greeter-qt6
"
	for i in $conflicts; do
		dpkg-divert --package task-a733-xorg --divert "$i.bak" --rename "$i"
	done
	;;
esac

#DEBHELPER#

exit 0
