#!/bin/sh

set -e

#DEBHELPER#

case $1 in
remove)
	conflicts="
/usr/lib/xorg/modules/libglamoregl.so /usr/bin/Xorg
/usr/lib/xorg/modules/drivers/modesetting_drv.so
"
	for i in $conflicts; do
		dpkg-divert --package xserver-xorg-img-bxm-1.21.1-2.deb --rename --remove "$i"
	done
	conflicts="
/usr/share/wayland-sessions/plasma.desktop /usr/bin/plasma-discover  /usr/bin/sddm-greeter-qt6
"
	for i in $conflicts; do
		dpkg-divert --package task-a733-xorg --rename --remove "$i"
	done
	;;
esac

exit 0
